"""
Data model for rectangles, spans, lines, blocks, character categories, and
alignment predicates. Coordinate convention follows PDF (origin bottom-left, y increases upward).
``Rect`` is constructed as ``Rect(left, right, top, bottom)``. A few internal
storage fields are implementation details; public callers should use the semantic accessors.
"""

import math
import re
import unicodedata
from collections.abc import Iterator
from decimal import ROUND_HALF_UP, Decimal
from typing import Any, Optional, Protocol

import regex as regex_module  # supports Unicode \p{...} property classes

from .block import (
    _COMBINING_MARKS,
    Block,
    _strip_diacritics,
    alignment_code,
    argmax_key,
    block_text,
    case_signal,
    deaccented_text,
    dominant_font_size,
    dominant_style_of,
    first_span_of,
    heading_score,
    is_caps_heavy,
    is_sentence_like,
    iter_sorted_children,
    last_line_of,
)
from .char_stats import (
    _MINUS_SIGN_CHARS,
    _SENTENCE_END_CHARS,
    _UNICODE_WHITESPACE_CHARS,
    _UNICODE_WHITESPACE_CLASS,
    CharStats,
    _max_nan_propagating,
    _min_nan_propagating,
    _round_half_up_to_int,
    _trim_unicode_ws,
    char_category,
    info_weight,
    is_punct_category,
    is_upper_dominant,
    is_word_category,
    letter_count,
    merge_char_stats,
    punct_count,
)
from .numbering import (
    _BRACKETED_NUM_RE,
    _NUMBERING_PREFIX_RE,
    _TO_NUMBER_BIN,
    _TO_NUMBER_DEC,
    _TO_NUMBER_HEX,
    _TO_NUMBER_INF,
    _TO_NUMBER_OCT,
    _detect_numbering,
    numbering_kind,
    numbering_text,
    numbering_value,
    to_number,
)
from .rects import (
    EMPTY_RECT,
    Bounded,
    Rect,
    RectLike,
    center_aligned,
    cmp_bottom_edge,
    cmp_left_edge,
    cmp_reading_order,
    extend_bottom_to,
    extend_top_to,
    intervals_overlap,
    left_aligned,
    left_edge_key,
    magnitude_ratio,
    reading_order_key,
    rect_intersection,
    rect_union,
    right_aligned,
    same_x_extent,
    same_y_extent,
    x_aligned,
    x_centers_close,
    y_overlaps,
)
from .span_line import (
    _ONE_DECIMAL_QUANTUM,
    Line,
    Span,
    _bold_font_re,
    _font_name_aliases,
    _format_half_up_one_decimal,
    _HasCharCount,
    _italic_font_re,
    _subset_prefix_re,
    append_span,
    avg_char_width,
    avg_char_width2,
    last_span,
    raw_text_of_line,
    style_key,
    text_of_line,
)

__all__ = [
    "EMPTY_RECT",
    "Block",
    "Bounded",
    "CharStats",
    "Line",
    "Rect",
    "RectLike",
    "Span",
    "alignment_code",
    "append_span",
    "argmax_key",
    "avg_char_width",
    "avg_char_width2",
    "block_text",
    "case_signal",
    "center_aligned",
    "char_category",
    "cmp_bottom_edge",
    "cmp_left_edge",
    "cmp_reading_order",
    "deaccented_text",
    "dominant_font_size",
    "dominant_style_of",
    "extend_bottom_to",
    "extend_top_to",
    "first_span_of",
    "heading_score",
    "info_weight",
    "intervals_overlap",
    "is_caps_heavy",
    "is_punct_category",
    "is_upper_dominant",
    "is_word_category",
    "iter_sorted_children",
    "last_line_of",
    "last_span",
    "left_aligned",
    "left_edge_key",
    "letter_count",
    "magnitude_ratio",
    "merge_char_stats",
    "numbering_kind",
    "numbering_text",
    "numbering_value",
    "punct_count",
    "raw_text_of_line",
    "reading_order_key",
    "rect_intersection",
    "rect_union",
    "right_aligned",
    "same_x_extent",
    "same_y_extent",
    "style_key",
    "text_of_line",
    "to_number",
    "x_aligned",
    "x_centers_close",
    "y_overlaps",
]
