"""A workbook read as a workbook: coordinates, formulas, styles, tables, charts.

FrontierAgent's ``_reader_xlsx.py`` is the reference (audit D29-D45) and this is a port of
it, with one deliberate difference recorded in ``xlsx.py``'s own docstring: the grid is
tab-separated rather than a markdown pipe table, because ``normalize_for_quote_match``
folds whitespace away and keeps ``|``, so a quotation spanning two cells can verify against
one and never against the other. ``test_two_adjacent_cells_verify_as_one_quotation`` is
that difference, asserted rather than asserted-about.

Every fixture is generated by openpyxl here rather than committed: a binary in the tree is
a thing nobody can review in a diff.
"""
from __future__ import annotations

import datetime
import importlib

import pytest

from misaka.core.documents.office import xlsx

openpyxl = importlib.import_module("openpyxl")


def _book(tmp_path, name="book.xlsx"):
    from openpyxl import Workbook
    return Workbook(), str(tmp_path / name)


def _save(wb, path):
    wb.save(path)
    return path


# ── grid ────────────────────────────────────────────────────────────────────

def test_the_grid_carries_column_letters_and_row_numbers(tmp_path):
    wb, path = _book(tmp_path)
    ws = wb.active
    ws.title = "Revenue"
    ws["A1"], ws["B1"] = "year", "amount"
    ws["A2"], ws["B2"] = 2024, 1234
    out = xlsx.render(_save(wb, path))
    assert "## Sheet: Revenue" in out
    assert "\tA\tB" in out
    assert "1\tyear\tamount" in out
    assert "2\t2024\t1234" in out


def test_two_adjacent_cells_verify_as_one_quotation(tmp_path):
    """The reason the grid is not a markdown table. ``normalize_for_quote_match`` removes
    whitespace and keeps ``|``: under a pipe table "year amount" folds to "yearamount" and
    the page folds to "|year|amount|", so the quotation cannot be found. Tabs fold away."""
    from misaka.core.documents.index import normalize_for_quote_match

    wb, path = _book(tmp_path)
    ws = wb.active
    ws["A1"], ws["B1"] = "year", "amount"
    page = xlsx.render(_save(wb, path))
    assert normalize_for_quote_match("year amount") in normalize_for_quote_match(page)


def test_an_empty_row_inside_a_region_is_dropped_but_numbering_is_real(tmp_path):
    wb, path = _book(tmp_path)
    ws = wb.active
    ws["A1"], ws["A3"] = "top", "bottom"
    out = xlsx.render(_save(wb, path))
    assert "1\ttop" in out and "3\tbottom" in out
    assert "\n2\t" not in out


def test_two_data_islands_are_separated_and_labelled(tmp_path):
    wb, path = _book(tmp_path)
    ws = wb.active
    ws["A1"] = "first"
    ws["A9"] = "second"          # a gap of more than _GAP blank rows splits the block
    out = xlsx.render(_save(wb, path))
    assert "`data region 1: A1`" in out
    assert "`data region 2: A9`" in out


# ── rendered values ─────────────────────────────────────────────────────────

@pytest.mark.parametrize(("value", "fmt", "shown"), [
    (datetime.datetime(2024, 3, 1), None, "2024-03-01"),  # noqa: DTZ001 - a cell has no zone
    (datetime.datetime(2024, 3, 1, 14, 30, 5), None, "2024-03-01 14:30:05"),  # noqa: DTZ001
    (0.153, "0.0%", "15.3%"),
    (1234567.0, "#,##0", "1,234,567"),
    (1234.5, '"$"#,##0.00', "$1,234.50"),
    (-1234.0, "#,##0;(#,##0)", "(1,234)"),
    (12345.0, "0.00E+00", "1.23E+04"),
    (1234567.0, '#,##0,,"M"', "1234567"),   # trailing-comma scaling is not rendered
])
def test_number_formats_render_the_way_the_sheet_shows_them(tmp_path, value, fmt, shown):
    wb, path = _book(tmp_path)
    ws = wb.active
    ws["A1"] = value
    if fmt:
        ws["A1"].number_format = fmt
    assert shown in xlsx.render(_save(wb, path))


def test_a_number_format_is_recorded_once_at_sheet_level(tmp_path):
    wb, path = _book(tmp_path)
    ws = wb.active
    for row in range(1, 6):
        ws.cell(row=row, column=1, value=0.5).number_format = "0.0%"
    out = xlsx.render(_save(wb, path))
    assert "▸ number-format" in out
    assert "0.0% A1:A5" in out


# ── formulas ────────────────────────────────────────────────────────────────

def test_a_homogeneous_fill_is_one_grouped_r1c1_entry(tmp_path):
    wb, path = _book(tmp_path)
    ws = wb.active
    for row in range(1, 6):
        ws.cell(row=row, column=1, value=row)
        ws.cell(row=row, column=2, value=f"=A{row}*2")
    out = xlsx.render(_save(wb, path))
    assert "▸ formulas" in out
    assert "B1:B5 =RC[-1]*2" in out


def test_an_isolated_formula_keeps_its_a1_text(tmp_path):
    wb, path = _book(tmp_path)
    ws = wb.active
    ws["A1"], ws["C9"] = 1, "=SUM(A1:A5)"
    out = xlsx.render(_save(wb, path))
    assert "C9 =SUM(A1:A5)" in out


def test_a_formula_this_product_wrote_reads_back_as_uncached(tmp_path):
    """openpyxl cannot write a cached value, and neither can this product's writer: a
    workbook it produced has empty caches until something calculates them. Saying
    ``uncached`` is the honest answer -- a blank cell would read as "the formula is zero"."""
    wb, path = _book(tmp_path)
    ws = wb.active
    ws["A1"], ws["A2"] = 2, "=A1*3"
    out = xlsx.render(_save(wb, path))
    assert "`uncached`" in out
    assert "uncached" in out.split("## Sheet")[0]  # the head says why, once


# ── sheet-level meta ────────────────────────────────────────────────────────

def test_a_merged_region_names_the_cell_holding_the_value(tmp_path):
    wb, path = _book(tmp_path)
    ws = wb.active
    ws["A1"] = "title across three"
    ws.merge_cells("A1:C1")
    out = xlsx.render(_save(wb, path))
    assert "▸ merged" in out
    assert "A1:C1 (value at A1)" in out


def test_bold_and_fill_are_compressed_into_ranges(tmp_path):
    from openpyxl.styles import Font, PatternFill
    wb, path = _book(tmp_path)
    ws = wb.active
    for row in range(1, 4):
        cell = ws.cell(row=row, column=1, value=f"r{row}")
        cell.font = Font(bold=True)
        cell.fill = PatternFill("solid", fgColor="FFFF0000")
    out = xlsx.render(_save(wb, path))
    assert "▸ styles" in out
    assert "bold: A1:A3" in out
    assert "#FF0000 A1:A3" in out


def test_a_hyperlink_and_a_comment_are_kept(tmp_path):
    from openpyxl.comments import Comment
    wb, path = _book(tmp_path)
    ws = wb.active
    ws["A1"] = "source"
    ws["A1"].hyperlink = "https://example.org/paper"
    ws["B1"] = "note"
    ws["B1"].comment = Comment("checked against the 2024 edition", "reviewer")
    out = xlsx.render(_save(wb, path))
    assert "▸ extras" in out
    assert "link A1→https://example.org/paper" in out
    assert 'comment B1:"checked against the 2024 edition"' in out


def test_a_dropdown_is_kept(tmp_path):
    from openpyxl.worksheet.datavalidation import DataValidation
    wb, path = _book(tmp_path)
    ws = wb.active
    ws["A1"] = "pick"
    validation = DataValidation(type="list", formula1='"yes,no"')
    ws.add_data_validation(validation)
    validation.add("A1:A9")
    out = xlsx.render(_save(wb, path))
    assert "dropdown A1:A9" in out


def test_conditional_formatting_is_kept(tmp_path):
    from openpyxl.formatting.rule import CellIsRule
    wb, path = _book(tmp_path)
    ws = wb.active
    ws["A1"] = 5
    ws.conditional_formatting.add(
        "A1:A9", CellIsRule(operator="greaterThan", formula=["3"]))
    out = xlsx.render(_save(wb, path))
    assert "▸ cond" in out
    assert "cellIs greaterThan 3" in out


# ── tables, pivots, charts ──────────────────────────────────────────────────

def test_a_small_excel_table_is_emitted_whole_with_no_column_schema(tmp_path):
    from openpyxl.worksheet.table import Table
    wb, path = _book(tmp_path)
    ws = wb.active
    ws.append(["name", "amount"])
    for n in range(1, 6):
        ws.append([f"row{n}", n * 10])
    ws.add_table(Table(displayName="Sales", ref="A1:B6"))
    out = xlsx.render(_save(wb, path))
    assert '▸ table "Sales": A1:B6 (5 data rows)' in out
    assert "▸ columns" not in out
    assert "name\tamount" in out
    assert "row5\t50" in out


def test_a_large_excel_table_gets_a_column_schema_and_a_preview(tmp_path):
    from openpyxl.worksheet.table import Table
    wb, path = _book(tmp_path)
    ws = wb.active
    ws.append(["name", "amount"])
    for n in range(1, 31):
        ws.append([f"row{n}", n])
    ws.add_table(Table(displayName="Big", ref="A1:B31"))
    out = xlsx.render(_save(wb, path))
    assert "▸ columns" in out
    assert "amount: num, min=1, max=30" in out
    assert "name: str, 30 uniq" in out
    assert f"▸ preview: first {xlsx.PREVIEW} rows" in out
    assert "row20\t20" in out
    assert "row21\t21" not in out


def test_a_chart_is_read_out_of_the_package(tmp_path):
    """openpyxl discards charts on load, so they are parsed from chart1.xml directly."""
    from openpyxl.chart import BarChart, Reference
    wb, path = _book(tmp_path)
    ws = wb.active
    ws.title = "Data"
    ws.append(["q", "v"])
    for n in range(1, 5):
        ws.append([f"Q{n}", n * 3])
    chart = BarChart()
    chart.title = "Quarterly"
    chart.add_data(Reference(ws, min_col=2, min_row=1, max_row=5), titles_from_data=True)
    chart.set_categories(Reference(ws, min_col=1, min_row=2, max_row=5))
    ws.add_chart(chart, "D2")
    out = xlsx.render(_save(wb, path))
    assert "▸ charts" in out
    assert "bar" in out
    assert 'title="Quarterly"' in out


# ── sheets ──────────────────────────────────────────────────────────────────

def test_an_empty_sheet_produces_no_page_of_its_own(tmp_path):
    wb, path = _book(tmp_path)
    wb.active["A1"] = "only sheet with content"
    wb.create_sheet("Blank")
    out = xlsx.render(_save(wb, path))
    assert "## Sheet: Blank" not in out


def test_a_hidden_sheet_is_read_and_marked(tmp_path):
    """Owner decision D6: a hidden sheet is read. An archival workbook hides the sheet
    that holds the data more often than it hides junk, and missing data is the worse
    failure for a corpus. It is marked so a reader knows where the text came from."""
    wb, path = _book(tmp_path)
    wb.active["A1"] = "visible"
    hidden = wb.create_sheet("Workings")
    hidden["A1"] = "the number nobody meant to publish"
    hidden.sheet_state = "hidden"
    out = xlsx.render(_save(wb, path))
    assert "## Sheet: Workings (hidden)" in out
    assert "the number nobody meant to publish" in out


def test_a_workbook_with_no_content_anywhere_is_refused(tmp_path):
    wb, path = _book(tmp_path, "blank.xlsx")
    with pytest.raises(ValueError) as caught:
        xlsx.render(_save(wb, path))
    assert "blank.xlsx" in str(caught.value)


# ── cell_range ──────────────────────────────────────────────────────────────

def test_cell_range_renders_only_that_region(tmp_path):
    wb, path = _book(tmp_path)
    ws = wb.active
    ws.title = "S"
    for row in range(1, 11):
        ws.cell(row=row, column=1, value=f"row{row}")
    out = xlsx.render(_save(wb, path), cell_range="S!A2:A3")
    assert "row2" in out and "row3" in out
    assert "row9" not in out


def test_an_unknown_sheet_in_a_cell_range_names_the_sheets_there_are(tmp_path):
    wb, path = _book(tmp_path)
    wb.active.title = "Real"
    wb.active["A1"] = "x"
    with pytest.raises(ValueError) as caught:
        xlsx.render(_save(wb, path), cell_range="Ghost!A1:B2")
    assert "Ghost" in str(caught.value)
    assert "Real" in str(caught.value)


def test_a_malformed_cell_range_says_so(tmp_path):
    wb, path = _book(tmp_path)
    wb.active["A1"] = "x"
    with pytest.raises(ValueError) as caught:
        xlsx.render(_save(wb, path), cell_range="not a range")
    assert "not a range" in str(caught.value)


# ── csv / tsv ───────────────────────────────────────────────────────────────

def test_a_csv_is_a_relational_table_with_column_meta(tmp_path):
    path = tmp_path / "rows.csv"
    body = "name,amount\n" + "".join(f"r{n},{n}\n" for n in range(1, 31))
    path.write_text(body, encoding="utf-8")
    out = xlsx.render_csv(str(path))
    assert "▸ table" in out
    assert "amount: num, min=1, max=30" in out
    assert "r30,30" in out           # csv is never truncated: paging is the layer above


def test_a_csv_line_verifies_exactly_as_the_file_writes_it(tmp_path):
    """A workbook has no textual form, so its grid can use tabs. A csv *is* text, and a
    reader quotes the line as it stands -- so the rows go back out through ``csv.writer``
    on the source dialect and round-trip, quoting included. Rendering them with tabs made
    ``verify_quote("North,800")`` fail against the file that literally contains it."""
    from misaka.core.documents.index import normalize_for_quote_match

    path = tmp_path / "regions.csv"
    path.write_text('region,units,note\nNorth,800,"a, with a comma"\nSouth,440,plain\n',
                    encoding="utf-8")
    out = xlsx.render_csv(str(path))
    folded = normalize_for_quote_match(out)
    assert normalize_for_quote_match("North,800") in folded
    assert normalize_for_quote_match('"a, with a comma"') in folded


def test_a_tsv_splits_on_tabs(tmp_path):
    path = tmp_path / "rows.tsv"
    path.write_text("name\tamount\nalpha\t1\n", encoding="utf-8")
    out = xlsx.render_csv(str(path))
    assert "alpha\t1" in out


def test_a_non_utf8_csv_is_decoded_rather_than_mangled(tmp_path):
    """The corpus decodes strictly through ``index._decode_bytes``; hardcoding utf-8 turns
    a Shift-JIS data file into replacement characters that then verify against nothing."""
    path = tmp_path / "jp.csv"
    path.write_bytes("題名,数\n吾輩は猫である,1\n".encode("cp932"))
    out = xlsx.render_csv(str(path))
    assert "吾輩は猫である" in out


def test_an_empty_csv_is_refused(tmp_path):
    path = tmp_path / "nothing.csv"
    path.write_text("", encoding="utf-8")
    with pytest.raises(ValueError) as caught:
        xlsx.render_csv(str(path))
    assert "nothing.csv" in str(caught.value)


# ── size guard ──────────────────────────────────────────────────────────────

def test_a_region_too_large_to_grid_degrades_to_its_reference(tmp_path, monkeypatch):
    """A dense island of a million cells is not rendered into the model's context; it is
    named, with the argument that fetches part of it."""
    monkeypatch.setattr(xlsx, "MAX_GRID_CELLS", 4)
    wb, path = _book(tmp_path)
    ws = wb.active
    for row in range(1, 4):
        for col in range(1, 4):
            ws.cell(row=row, column=col, value=row * col)
    out = xlsx.render(_save(wb, path))
    assert "cell_range" in out
    assert "A1:C3" in out


@pytest.mark.parametrize("rng", ["S!A:B", "S!2:3", "S!B"])
def test_a_whole_column_or_row_range_is_filled_from_the_sheet(tmp_path, rng):
    """openpyxl half-accepts these: ``range_boundaries`` returns None for the bound the
    argument did not give, which used to reach the grid and die on ``None + 1`` -- a bare
    TypeError out of a tool call, which a model cannot act on. FrontierAgent has the same
    crash. The missing bounds come from the sheet's extent, which is what was meant."""
    wb, path = _book(tmp_path)
    ws = wb.active
    ws.title = "S"
    for row in range(1, 5):
        ws.cell(row=row, column=1, value=f"a{row}")
        ws.cell(row=row, column=2, value=f"b{row}")
    out = xlsx.render(_save(wb, path), cell_range=rng)
    assert "`cell_range:" in out
    assert "\t" in out


# ── defects an adversarial read of FrontierAgent's source turned up ──────────
#
# Each of these is a real defect in the reference implementation, found by reading it and
# reproduced here before the fix was written. They are the reason this port is not a
# transcription.

def test_an_uncached_formula_inside_an_excel_table_is_marked_too(tmp_path):
    """The head promises "empty formula caches marked uncached". FrontierAgent's
    ``_x_table_regions`` takes no ``mark_uncached``, so inside an Excel Table the same cell
    renders as nothing at all -- and a blank cell reads as "this formula is empty"."""
    from openpyxl.worksheet.table import Table
    wb, path = _book(tmp_path)
    ws = wb.active
    ws.append(["name", "double"])
    for n in range(1, 4):
        ws.append([f"r{n}", f"=A{n + 1}"])
    ws.add_table(Table(displayName="T", ref="A1:B4"))
    out = xlsx.render(_save(wb, path))
    assert out.count("`uncached`") >= 3


def test_a_region_whose_cells_all_render_empty_is_not_announced(tmp_path):
    """``=IF(A1>0,A1,"")`` caches an empty string: non-empty to the coordinate scan, empty
    to the renderer. Announcing a region and then showing no rows asserts that something is
    there and says nothing about it."""
    wb, path = _book(tmp_path)
    ws = wb.active
    ws["A1"], ws["B1"] = "", ""
    ws["A5"] = "real content"
    out = xlsx.render(_save(wb, path))
    assert "`data region" in out          # the real one survives
    assert "real content" in out
    assert "\tA\tB\n" not in out          # the all-empty one is not announced


def test_a_chart_whose_data_sheet_is_gone_is_still_reported(tmp_path):
    """A chart is filed under the sheet its data is on. When no worksheet claims that name
    -- an external reference, a deleted sheet -- FrontierAgent drops it silently: its
    fallback only catches the unparseable case."""
    wb, path = _book(tmp_path)
    wb.active["A1"] = "content"
    _save(wb, path)
    real = xlsx._chart_lines
    try:
        xlsx._chart_lines = lambda p: {"Ghost": ["bar series='Ghost'!$A$1:$A$4"]}
        out = xlsx.render(path)
    finally:
        xlsx._chart_lines = real
    assert "▸ charts" in out
    assert "Ghost" in out


def test_a_cell_range_point_query_does_not_scan_the_whole_workbook(tmp_path):
    """Asking for two cells must not walk every cell of every sheet -- which is also what
    decides whether a 90-second recalculation subprocess is worth starting."""
    wb, path = _book(tmp_path)
    ws = wb.active
    ws.title = "S"
    for row in range(1, 200):
        ws.cell(row=row, column=1, value=row)
    _save(wb, path)
    seen = []
    real = xlsx._has_formula
    try:
        xlsx._has_formula = lambda cell: seen.append(1) or real(cell)
        xlsx.render(path, cell_range="S!A1:A2")
    finally:
        xlsx._has_formula = real
    assert len(seen) <= 8          # the four cells of the range, twice over at worst


def test_a_chart_sheet_in_a_cell_range_is_refused_rather_than_crashing(tmp_path):
    """A chartsheet is in ``sheetnames`` and has no ``.cell``; reaching the grid with one
    raised a bare AttributeError out of the tool call."""
    from openpyxl.chart import BarChart
    wb, path = _book(tmp_path)
    wb.active["A1"] = 1
    sheet = wb.create_chartsheet("Picture")
    sheet.add_chart(BarChart())
    _save(wb, path)
    with pytest.raises(ValueError) as caught:
        xlsx.render(path, cell_range="Picture!A1:B2")
    assert "chart sheet" in str(caught.value)


def test_a_chart_title_split_across_runs_keeps_its_spaces_and_its_quotes(tmp_path):
    """``"".join`` over the title's text nodes runs words together, and a title carrying a
    quote closes the ``title="..."`` attribute early."""
    from openpyxl.chart import BarChart, Reference
    wb, path = _book(tmp_path)
    ws = wb.active
    ws.title = "D"
    ws.append(["q", "v"])
    for n in range(1, 4):
        ws.append([f"Q{n}", n])
    chart = BarChart()
    chart.title = 'Revenue "2024" by quarter'
    chart.add_data(Reference(ws, min_col=2, min_row=1, max_row=4), titles_from_data=True)
    ws.add_chart(chart, "D2")
    out = xlsx.render(_save(wb, path))
    assert "Revenue" in out and "by quarter" in out
    assert 'title="Revenue' in out
    assert out.count('title="') == 1        # the attribute was not closed early
